### ISSUE TITLE
what cuda version

### ISSUE THREAD

**Issue by lz2411** [andyzeng/tsdf-fusion#14]
Hi,thank you for publishing your code. 

Can i ask what version of CUDA are you using? I used 9.1 and it is encounter an fatal error with cudaMalloc when running demo. 
My nvidia driver version is 384.111 and graphic processor is Quadro M2200.

**Comment by andyzeng** [comment]
I am using CUDA 8.0.
Could you paste the fatal error message? (in particular, the specific fatal error code)

**Comment by lz2411** [comment]
checkCUDA(__LINE__, cudaGetLastError())

The first checkCUDA in demo.cu. It says fatal error with Cuda, no detailed error.  Maybe it's because I used cuda9. 1? Any idea? Thank you.

**Comment by andyzeng** [comment]
Could you copy paste the printout from your console? (or take a screenshot)
Printing "FatalError" comes from a helper function in [utils.hpp](https://github.com/andyzeng/tsdf-fusion/blob/master/utils.hpp)

**Comment by lz2411** [comment]
![error_cuda](https://user-images.githubusercontent.com/10576107/38016118-f65c4626-3265-11e8-975f-85c2bd832c0e.png)
Thank you for the help.

**Comment by andyzeng** [comment]
Your console prints CUDA failure code: 35. From cudaError_t (found in the driver_types.h file), this means:
```
     /**
     * This indicates that the installed NVIDIA CUDA driver is older than the
     * CUDA runtime library. This is not a supported configuration. Users should
     * install an updated NVIDIA display driver to allow the application to run.
     */
     cudaErrorInsufficientDriver           =     35,
```
It looks like you're having this error because your NVIDIA display driver 384.111 is not compatible with CUDA 9.1. Try downgrading to CUDA 9, or upgrading your display driver to 390.12. Some instructions [here](https://devtalk.nvidia.com/default/topic/1028960/cuda-setup-and-installation/looking-for-cuda-compatibility-chart-for-nvidia-drivers/).

**Comment by lz2411** [comment]
Thank you for the notes. 
It was resolved. I put in CUDA 8.0 but couldn't directly install the default NVIDA 375. This kernel i am using 4.3.0-37 doesn't run 390 or 375. Eventually, it was fixed by installing a transnational package (can be found in Synaptic).
